schema/Organization.schema.md
schema/Organization.schema.yaml

Another refinement:
* Organization already has `brand` so no need for `logo`
* `owns` removed as discussed earlier today
Plus a typo fix

fix: typo in Organization and removed logo and owns

---

schema/Product.schema.yaml

My over-diligence bites back. Since `product` has a property `brand` which includes `logo`, product itself doesn't need it.

fix: remove logo from product since brand already has it

---

Gulpfile.js
examples/datatables/simple.datatable.yaml
schema/Article.schema.yaml
schema/Collection.schema.yaml
schema/CreativeWork.schema.yaml
schema/Node.schema.yaml
schema/Thing.schema.yaml
schema/data/Datatable.md
schema/data/Datatable.schema.yaml
schema/data/DatatableColumn.schema.yaml
schema/data/DatatableColumnSchema.schema.yaml
schema/index.schema.yaml
schema/json-schema-draft-07.schema.json
schema/software/Expression.schema.yaml
schema/text/Blockquote.schema.yaml
schema/text/Heading.schema.yaml
schema/text/Paragraph.schema.yaml
schema/text/Table.schema.yaml
schema/text/TableCell.schema.yaml
schema/text/inlineContent.schema.yaml

This adds a number of types and properties as found necessary for conversion of `xlsx`, `csv` and `datapackage.json` files in the `stencila/convert` repo. Merging in now to get a release for use in that repo.

Updates, most around Datatables, necessary for converter

---

package-lock.json
package.json
schema/organization/Person.schema.yaml
schema/organization/Person.ts
tests/Person.test.ts
util.ts

This introduces the custom keyword `parser` to schema definitions.
Parsers allow users to enter shorter, and varying, string formats for nodes e.g. `John Tom` for an array of `givenNames` instead of `["John", "Tom"]`.
To use parsers schema authors need to add the `parser` keyword to the `.schema.yaml` file and, where necessary, write a parser function that takes a string and returns the desired node. See `Person.schema.yaml` and `Person.ts` for an example.

Add parser keyword

---

.gitignore
.prettierignore
Gulpfile.js
package-lock.json
package.json
schema/organization/Person.schema.yaml
schema/organization/Person.ts
tests/Person.test.ts
util.ts

This is necessary for distributing as a package.  The file `util.ts` needs to load the JSON Schema files at run time (we may take a different approach like bundling in the future but this applies nonetheless). So when distributed as a package the path for these can't be `path.join(__dirname, 'dist', ...)` as it currently is.

Generate schema.json files in "built" directory

---

.gitignore
.prettierignore
Gulpfile.js
package-lock.json
package.json
schema/organization/Person.schema.yaml
schema/organization/Person.ts
tests/Person.test.ts
tests/util.test.ts
util.ts

This PR allows authors to use aliases when creating nodes. Combined with the coercion of `mutate()` this allows for more convenient and permissive authoring of data.
For example, when adding YAML frontmatter to a markdown article, instead of using canonical property names,
```yaml
authors:
- givenNames:
- Tom
- familyNames:
- Smith
```
Authors could use aliases instead of names, and scalars instead of arrays,
```yaml
authors:
- firstName: Tom
lastName: Smith
```
Unfortunately, Ajv does not currently [coerce object into arrays](https://github.com/epoberezkin/ajv/issues/992) so this is not possible right now:
```yaml
author:
firstName: Tom
lastName: Smith
```
Aliases are automatically added for properties of `type: array` whose name ends with `s` e.g. the alias `givenName` is generated for …

Allow for property aliases

---

examples/list/nested.list.yaml
examples/list/simple.list.yaml
schema/text/List.md
schema/text/List.schema.yaml
schema/text/ListItem.md
schema/text/ListItem.schema.yaml

Changes `List` schema to require items to be of type `ListItems`, but then in turn opens up the `ListItem` schema to allow any `Node` type as children.

Update List & ListItem schemas

---

.vscode/settings.json
examples/link/simple.link.yaml
examples/link/withRelationship.link.yaml
examples/paragraph/nested.paragraph.yaml
examples/paragraph/simple.paragraph.yaml
examples/quote/attributed.quote.yaml
examples/quote/simple.quote.yaml
examples/quoteBlock/attributed.quoteBlock.yaml
examples/quoteBlock/simple.quoteBlock.yaml
examples/strong/nested.strong.yaml
examples/strong/simple.strong.yaml
examples/thematicBreak/simple.thematicBreak.yaml
schema/Link.md
schema/Paragraph.md
schema/Quote.md
schema/Quote.md~Stashed changes
schema/QuoteBlock.md
schema/Strong.md
schema/ThematicBreak.md

Part of the schema documentation initiative (#82)
Adds schemas for:
-  Link
-  Paragraph
-  Quote
-  QuoteBlock
-  Strong
-  ThematicBreak
The commits are atomic per schema, so might be easier to review them as such.

Add more schema documentation

---

package-lock.json
package.json
scripts/docs.ts

Closes #87 
Some changes:
- The table of properties links to the relative schemas, `type`s are wrapped in `<code>` tags
- Made refinements in Thema to fix syntax highlighting and adjustments to layouts
- Status is appended to the title
- Role is added below the title, though I think it could use clarification about the implications
- Adds a new `docs:serve` command for running a Browser Sync session to automatically reload the browser when documentation is rebuilt. For now the documentation build process has to be manually triggered.
Let me know if you think additional information could be surfaced. Wasn't sure if we wanted to link to the raw schema JSON under the `$id` field.
Relates to: https://github.com/stencila/thema/pull/8 (Though since Thema is a dependency of Encoda, Encoda will …

Improve generated documentation

---

examples/table/header.table.yaml
examples/table/irregularHeader.table.yaml
schema/TableCell.schema.yaml
schema/TableRow.schema.yaml

Closes #91 
Would appreciate feedback
Some notes, using HTML tags for demonstration:
- The idea is that if `kind: header/footer` is set on `TableRow` then the children could be wrapped in a `<thead>/<tfoot>` element, and the `kind: header` would be the default value when iterating over the children cells.
- For `TableCell` schema, the `kind` property can be either a `header` or `data`. The `data` variant is the default value and can be used to override the implicit `header` value passed from the the parent `TableRow` schema.
Couple of points for consideration:
- This does not implement something like the [HTML `scope` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th#attr-scope). I can see semantic benefits from using it, but can see it translating to only JATS and …

feat(Table): Add properties to indicate header cells

---

.travis.yml

This reduces lint/test/build time of the R package from about 8 mins to about 6 mins. Not a great improvement, but the best that seems possible given dev packages required.

Speed up R build on Travis

---

package.json
ts/util/__tests__/guards.test.ts
ts/util/guards.ts

Closes #115.
Added `isa` function. Might be better named `isType`. There may be a better implementation.

feat(Typescript): Add a more convienient single-type type guard

---

.travis.yml
package.json

When installing `@stencila/dev-config` we run some post-install scripts to [update the dependant package's `package.json`](https://github.com/stencila/dev-config/tree/master/packages/dev-config#install) file. Locally it's not too much of an issue since a user can compare and keep/discard the changes. However on CI this ended up [reverting some changes](https://github.com/stencila/schema/commit/c4da990d53fbd83718a52d703e702c075d02c30e) made to the package.json file.
This PR adds a step on CI to discard any changes to package.json file before running any release/deploy steps.

Avoid package.json regressions when installing on CI

---

ts/util/guards.ts

Needed for the typeguards to work on potentially `undefined` node values.

Allow typeGuards to work on undefined nodes

---

py/stencila/schema/types.py
r/R/types.R
schema/Cite.schema.yaml

Closes #133 
I didn't change the `target` prop to allow for holding either `string` or `CreativeWork`. After reading the reasoning for omitting the `content` prop, I think it doesn't make sense to have the CreativeWork content both in references and the cite node.
Let me know if someone feels otherwise :)

Add content field to Cite schema

---

package-lock.json
package.json
ts/bindings/utils.ts
tsconfig.lib.json

This PR allows building the project as multiple formats for consumption by other tools.
This fixes errors faced in tools like Rollup complaining about `Error: "[name] is not exported by '@stencila/schema'"` as outlined [here](http://rollupjs.org/guide/en/#error-name-is-not-exported-by-module) and [here](https://github.com/rollup/rollup/issues/2655#issuecomment-454735305).
I tried the built library as an NPM linked package in Encoda, Designa, and another project and seems to have worked.
We could first publish a release candidate to make sure there aren't any regressions.

Refactor library bundling process

---

py/stencila/schema/types.py
r/R/types.R
schema/BlockContent.schema.yaml
schema/InlineContent.schema.yaml
schema/Math.schema.yaml
schema/MathBlock.schema.yaml
schema/MathFragment.schema.yaml
ts/bindings/__file_snapshots__/BlockContent.R
ts/bindings/__file_snapshots__/BlockContent.py
ts/bindings/__file_snapshots__/BlockContent.ts

Closes #154. 
There is a sister PR on Encoda, https://github.com/stencila/encoda/pull/383, that does some testing that this structure & hierarchy will work for the Pandoc and HTML codecs.
No documentation added as yet, will wait for acceptance of this PR first.

feat(Math): Add Math, MathFragment and MathBlock node types

---

package-lock.json
package.json

This PR updates the Encoda dependency, which is desirable as fixes rendering markdown comments as `Null`s.

chore(Deps): Update dependencies

---

package-lock.json
package.json

Temporarily downgrades Microbundle due to changes in the output path of the TypeScript definition files.
I believe issues were introduced due to this commit: https://github.com/developit/microbundle/pull/646

fix(TS): Fix Typescript definition file path

---

ts/docs.ts

Close #202 
Error was due to flattening the sub-type array too early before `interspersing` the ` & ` and ` | ` combinator strings.

docs(TS): Fix type doc generation

---

.Rprofile
.dockerignore
Dockerfile
Makefile
README.md
docs/developing-docker.md
package.json
py/tox.ini

@nokome here is the start of work to create a Dockerized development environment! The user should be able to build this container, shell in (with working files mounted with volume) and then run `make docs`, etc. I'm not sure about the R/python/npm dependencies so this is as far as I got. Please push to /update this branch to make it work! This will make it easier to test and add the additional documentation files for #214  
Signed-off-by: vsoch <vsochat@stanford.edu>

adding start of work for dockerized development environment

---

py/stencila/schema/types.py
r/R/types.R
schema/Organization.schema.yaml

As discussed with Nokome, this change will allow us to better capture information about Article group authors (see https://github.com/stencila/encoda/issues/690, and https://github.com/stencila/encoda/issues/691).

feat(Organization): Add members field

---

schema/CodeError.schema.yaml

Otherwise coercion fails https://travis-ci.org/github/stencila/thema/builds/730301506#L1031
The [coerce function in Encoda](https://github.com/stencila/encoda/blob/master/src/util/coerce.ts#L99) does not attempt to read property aliases, and will attempt to read the `message` field on the schema during coercion. As no such property exists it will fail.
Not sure if making Encoda coercion more generous is worthwhile, as it shouldn't affect user-land schema authorship. It only has implications for Schema type definitions.
Going to merge, but would like you to be aware of the above note @nokome.

fix(CodeError): Match required key to property name

---

schema/CreativeWork.schema.yaml
schema/SoftwareSourceCode.schema.yaml
ts/util/jsonld.test.ts
ts/util/microdata.test.ts

Maintainer is now a schema.org property on https://schema.org/CreativeWork.

fix(CreativeWork): Move `maintainer` property from `SoftwareSourceCode` to `CreativeWork`.

---

schema/Comment.schema.yaml
schema/CreativeWork.schema.yaml
schema/Review.schema.yaml

Please see #227 the rationale for this PR.
@BlueRezz, you and your team might be interested in this. Would appreciate any thoughts or suggestions!

Add Review and Comment types

---

py/stencila/schema/types.py
r/R/types.R
schema/Cite.schema.yaml
schema/CiteGroup.schema.yaml

As part of our work on https://github.com/stencila/encoda/pull/842 we found that we did not have a `citationMode` variant for "author and year in-text". Instead of just adding one, I have taken the opportunity to rename the variants to make them a little more semantic and tool-agnostic (previously the variant name were Pandoc-centric) and also added `narrative-author` variant.
I suppose my main question here is. Do we want to to use these variant names, or for instance go with something like `textual` or `in-text`.
@alex-ketch This will allow us to properly implement citation styles in Thema e.g. orphan `Cite` nodes (not in a `CiteGroup`) with `citationMode: narrative-year` should not have parentheses around them and the year element should not be displayed whereas `citationMode: …

fix(Cite): Alter citation modes; add docs

---

schema/Claim.schema.yaml

A very first attempt at a `Claim` spec.
See discussion in https://github.com/stencila/encoda/issues/885
Not quite sure about `title` and `claimType`. Should the kind be pre-specified, not sure ...

feat(Claim): Claim type
